version: '3'
services:
  mongo:
    image: drannoc/mongosail
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_FILEPATH=/data/logs/logs
      - MONGO_DAEMON=1
      # --file must be a path inside of the virtual volume
      - MONGO_IMPORT=--type json --file /data/import.json
    volumes:
      # Used for MONGO_IMPORT
      - ./db/import.json:/data/import.json
      - ./db/logs:/data/logs
    ports:
      - 27017:27017

# This configuration will run mongo as a daemon allowing to use mongoimport right after mongo starts
# while writing logs to /data/logs/logs (./data/logs/logs on physical volume)